JuliaOpt/juliaopt.github.io

- index.html
hopefully I html'ed this right
> add CoinOptServices.jl to solver table

- index.html
> more citations

- index.html
> point to AmplNLWriter for bonmin and couenne

- packages/index.md
> added PowerModels.jl to network optimization list

- packages/index.md
CC @joehuchette @chriscoey @rdeits @ameliaperry : do the descriptions look good for you ?
> Add PolyJuMP and SumOfSquares in packages list

- packages/index.md
@joehuchette Is there a reason it wasn't already there ?
> Add StructJuMP in packages list

- _includes/solver-tables.html
> Add CSDP in solvers table

- _includes/overview.svg
- index.md
- learning/index.md
- packages/index.md
Not the most beautiful text, but I wanted to update the website quickly to track the new reorganization.
CC @pkofod
> update to reflect reorganization of GitHub organizations

- _includes/solver-tables.html
> list pajarito in solver table

- developersmeetup/index.md
Useful for translating Boston time to local time :)
> Add links to timeanddate

- showcase/index.md
Both were already listed in the julialang website
> Add universities to list

- developersmeetup/index.md
@joehuchette @chriscoey @juan-pablo-vielma
@blegat, I'm assuming you don't need the links to timeanddate.com anymore.
> remove timeanddate links and add youtube links

- packages/index.md
> discussion on using JuMP in package names

- meetings/bordeaux2018/index.md
The last sentence is to address the question, "why not schedule this during JuliaCon?"
> expand on the purpose and interest areas of the workshop

- meetings/bordeaux2018/index.md
do we really needed that sentence? it might be a negative stimulus...
> remove sentence about not acomodating all

- meetings/bordeaux2018/index.md
> Add committee affiliations

- index.md
- meetings/bordeaux2018/index.md
I set the dates of the workshop to June 27-29 and removed specifics about the schedule. This leaves room to shift things around, we just have a commitment to hold some collaboration/hacking time on Friday.
I also set a submission deadline of March 15th.
@odow @joaquimg @blegat @juan-pablo-vielma
> adjust dates and calendar for bordeaux

- meetings/bordeaux2018/index.md
> tweak description of workshop talks

- index.md
Let's flip the switch?
@odow @blegat @joaquimg
> Public link to JuMP-dev 2018

- meetings/bordeaux2018/index.md
This is consistent with a couple of the talks from last year, and wouldn't hurt for this year. What do you think?
@odow @blegat @joaquimg @juan-pablo-vielma
> List significant applications as an interest area of JuMP-dev

- _includes/solver-tables.html
Added OSQP to the solvers table
> Added OSQP

- meetings/bordeaux2018/index.md
I've gotten a few questions about what the email to the committee should contain; this will help clarify. I'd also like to do another round of invitations, so let's push the date back a bit.
@odow @blegat @joaquimg @juan-pablo-vielma @IssamT
> add a sign-up form and push date to april 7th

- meetings/bordeaux2018/index.md
- add schedule
- remove call for talks (I've already changed the Google form)
> Updates from meeting.

- packages/index.md
* Added LightGraphsFlows package below LightGraphs
* Detailed what is in LightGraphs, interface + simple implementation
> Added LightGraphsFlows package

- meetings/bordeaux2018/index.md
> close submissions for travel support

- meetings/bordeaux2018/index.md
I miss-spelt @xhub's name
@juan-pablo-vielma is it too late to correct the PDF (and SVG) version of the poster that @issamt was printing?
> Correct Olivier's name

- meetings/bordeaux2018/index.md
> Add room details

- meetings/bordeaux2018/index.md
> Add instructions for the dinner

- showcase/index.md
> Add Unviersité de Bretagne Sud

- index.md
- meetings/santiago2019/index.md
> Add page for JuMP-dev III

- meetings/santiago2019/index.md
Closes #94 
@rocarvaj did I muck up the translation?
> Delay JuMP-dev III submission deadline

- meetings/santiago2019/index.md
I'll leave the Spanish translation to a more qualified person :)
> Add schedule

- meetings/santiago2019/index.md
@juan-pablo-vielma @rocarvaj
This synchronizes it closer with the english version.
> updates to the spanish version for santiago2019

- meetings/santiago2019/index.md
There was some confusion about these workshops. Is it correct that they'll be held in Spanish? @rocarvaj @juan-pablo-vielma
> mention language of Monday/Friday events

- meetings/santiago2019/index.md
@joaquimg I'm not sure which notebook to link to (or how to properly link to all three), so speak up if you don't like my choice :)
> Fix links to two notebooks

- packages/index.md
> Update solver link

- conferences/informs_2019.md
- index.md
> Announce JuMP-dev IV

- index.md
@odow @juan-pablo-vielma @IainNZ @joehuchette @blegat @joaquimg
> End of JuliaOpt

- robots.txt
They're all extremely out of date.
> Don't index JuliaOpt notebooks
